# Generated by Django 5.0.2 on 2024-02-17 20:01

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('rg', models.FileField(blank=True, null=True, upload_to=storage.models.rg_directory_path)),
                ('cpf', models.FileField(blank=True, null=True, upload_to=storage.models.cpf_directory_path)),
                ('certidao_nascimento', models.FileField(blank=True, null=True, upload_to=storage.models.certidao_nascimento_directory_path)),
            ],
        ),
    ]
