# Generated by Django 5.0.2 on 2024-02-20 19:32

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=100)),
                ('rg_frente', models.FileField(blank=True, null=True, upload_to=storage.models.rg_frente_directory_path)),
                ('rg_costas', models.FileField(blank=True, null=True, upload_to=storage.models.rg_costas_directory_path)),
                ('cpf', models.FileField(blank=True, null=True, upload_to=storage.models.cpf_directory_path)),
                ('certidao_nascimento', models.FileField(blank=True, null=True, upload_to=storage.models.certidao_nascimento_directory_path)),
                ('cnh_frente', models.FileField(blank=True, null=True, upload_to=storage.models.cnh_frente_directory_path)),
                ('cnh_costas', models.FileField(blank=True, null=True, upload_to=storage.models.cnh_costas_directory_path)),
                ('carteira_de_trabalho_pag_1', models.FileField(blank=True, null=True, upload_to=storage.models.carteira_de_trabalho_pag_1_directory_path)),
                ('carteira_de_trabalho_pag_2', models.FileField(blank=True, null=True, upload_to=storage.models.carteira_de_trabalho_pag_2_directory_path)),
                ('carteira_de_vascinacao', models.FileField(blank=True, null=True, upload_to=storage.models.carteira_de_vascinacao_directory_path)),
                ('comprovante_de_escolaridade', models.FileField(blank=True, null=True, upload_to=storage.models.comprovante_de_escolaridade_directory_path)),
                ('comprovante_de_residencia', models.FileField(blank=True, null=True, upload_to=storage.models.comprovante_de_residencia_directory_path)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to=storage.models.curriculo_directory_path)),
                ('exame_admissional', models.FileField(blank=True, null=True, upload_to=storage.models.exame_admissional_directory_path)),
                ('formulario_odonto', models.FileField(blank=True, null=True, upload_to=storage.models.formulario_odonto_directory_path)),
                ('formulario_vt', models.FileField(blank=True, null=True, upload_to=storage.models.formulario_vt_directory_path)),
                ('formulario_plano_de_saude', models.FileField(blank=True, null=True, upload_to=storage.models.formulario_plano_de_saude_directory_path)),
                ('reservista', models.FileField(blank=True, null=True, upload_to=storage.models.reservista_directory_path)),
                ('titulo_de_eleitor_frente', models.FileField(blank=True, null=True, upload_to=storage.models.titulo_de_eleitor_frente_directory_path)),
                ('titulo_de_eleitor_costas', models.FileField(blank=True, null=True, upload_to=storage.models.titulo_de_eleitor_costas_directory_path)),
                ('sus_frente', models.FileField(blank=True, null=True, upload_to=storage.models.sus_frente_directory_path)),
                ('sus_costas', models.FileField(blank=True, null=True, upload_to=storage.models.sus_costas_directory_path)),
                ('conta_bancaria', models.FileField(blank=True, null=True, upload_to=storage.models.conta_bancaria_directory_path)),
                ('pis', models.FileField(blank=True, null=True, upload_to=storage.models.pis_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
